# treta infotv terminals are aeons-old android that can't modern SSL
# so here's an example ingress to do just read-only stuff
# remember djangoapp_allowed_hosts

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: infotv-insecure
spec:
  rules:
  - host: infotv-insecure.tracon.fi
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: node
            port:
              number: 3000
